-- BBSIA — Bloco 'internacional' no catálogo (referências de IA de fora, ex.: DPG Registry).
-- Entram como curadoria-first (publicado=false, revisado=false), soberania=externo, com link
-- verificado. São referências internacionais, marcadas para distinguir das soluções brasileiras.

alter table public.catalogo_solucoes drop constraint catalogo_solucoes_bloco_check;
alter table public.catalogo_solucoes add constraint catalogo_solucoes_bloco_check
  check (bloco in ('gov','mgi','formulario','software_publico','internacional'));

-- 8 DPGs de IA de menor risco (curadoria: DPG Registry). publicado=false, revisado=false.
insert into public.catalogo_solucoes
  (titulo, descricao, orgao, area, status, nivel_risco, tipo_solucao, soberania, bloco,
   frameworks, modalidades, tags, licenca, link, revisado, publicado, fonte) values
  ('AI Agro','Agricultura de precisão com drones/UAV: avalia a saúde de culturas via machine learning e visão computacional. Referência internacional (em inglês).','RentadroneCL (Chile)','meio_ambiente','ativo','minimo','ferramenta','externo','internacional', array['Computer Vision','ML']::text[], array['imagem']::text[], array['Internacional','DPG','Chile']::text[],'GPL-3.0','https://github.com/RentadroneCL/Precision_Agriculture', false, false, 'DPG Registry'),
  ('Dymaxion Labs Toolkit','Análise de dados geoespaciais em larga escala com visão computacional e segmentação semântica (U-Net). Referência internacional (em inglês).','Dymaxion Labs (Argentina)','meio_ambiente','ativo','minimo','pipeline','externo','internacional', array['U-Net','Computer Vision']::text[], array['imagem']::text[], array['Internacional','DPG','Argentina']::text[],'Apache-2.0','https://github.com/dymaxionlabs/satproc', false, false, 'DPG Registry'),
  ('Zamba','Identifica espécies em vídeos de armadilhas fotográficas usando deep learning. Referência internacional (em inglês).','DrivenData (EUA)','meio_ambiente','ativo','minimo','modelo','externo','internacional', array['Deep Learning']::text[], array['imagem']::text[], array['Internacional','DPG','EUA']::text[],'MIT','https://github.com/drivendataorg/zamba', false, false, 'DPG Registry'),
  ('Koster Seafloor Observatory','Análise automática de vídeos submarinos (espécies e habitats) com ML de visão, treinado por ciência cidadã. Referência internacional (em inglês).','Ocean Data Factory (Suécia)','meio_ambiente','ativo','minimo','modelo','externo','internacional', array['Computer Vision','ML']::text[], array['imagem']::text[], array['Internacional','DPG','Suécia']::text[],'GPL-3.0','https://github.com/ocean-data-factory-sweden/koster_ml', false, false, 'DPG Registry'),
  ('OTTAA Project','Comunicação alternativa e aumentativa preditiva (IA) para pessoas com deficiência de fala. Referência internacional (em inglês).','OTTAA Project (Argentina)','saude','ativo','limitado','ferramenta','externo','internacional', array['NLP','Predição']::text[], array['texto']::text[], array['Internacional','DPG','Argentina','Acessibilidade']::text[],'GPL-3.0','https://github.com/OTTAA-Project/ottaa_project_flutter', false, false, 'DPG Registry'),
  ('Kindly','API que detecta intenção de bullying/abuso em mensagens de texto (NLP). Referência internacional (em inglês).','UNICEF','educacao','ativo','limitado','ferramenta','externo','internacional', array['NLP']::text[], array['texto']::text[], array['Internacional','DPG','UNICEF']::text[],'AGPL-3.0','https://github.com/unicef/kindly', false, false, 'DPG Registry'),
  ('iVerify','Plataforma de combate à desinformação e discurso de ódio (NLP). Referência internacional (em inglês).','UNDP','gestao_publica','ativo','limitado','ferramenta','externo','internacional', array['NLP']::text[], array['texto']::text[], array['Internacional','DPG','UNDP']::text[],'AGPL-3.0','https://github.com/undp/iVerify-Apps', false, false, 'DPG Registry'),
  ('I-Stem','Converte documentos inacessíveis em formatos acessíveis com IA (OCR/NLP). Referência internacional (em inglês).','I-Stem (Índia)','administracao','ativo','minimo','ferramenta','externo','internacional', array['OCR','NLP']::text[], array['imagem','texto']::text[], array['Internacional','DPG','Índia','Acessibilidade']::text[],'AGPL-3.0','https://github.com/i-stem/science', false, false, 'DPG Registry');
